apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: ci
spec:
  cpu:
    isolated: "2-3"
    reserved: "0-1"
  realTimeKernel:
    enabled: true
  numa:
    topologyPolicy: "single-numa-node"
